# Get all data talents
GET /talents HTTP/1.1
Host: localhost:8080

###

# Get data talent by id
@idAdd = 3
GET /talents/{{idAdd}} HTTP/1.1
Host: localhost:8080

###

# Add data talent
POST /talents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": 8,
  "name": "Andi",
  "batch": 4,
  "phone": "12345678",
  "address": "Demak"
}

###

# Edit data talent by id
@idEdit = 1
PATCH /talents/{{idEdit}} HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Itsna",
  "batch": 4,
  "phone": "0895367608879",
  "address": "Pati"
}

###

# Delete data talent by id
@id = 1
DELETE  /talents/{{id}} HTTP/1.1
Host: localhost:8080