# Get all users
GET /users HTTP/1.1
Host: localhost:8080

###

# Get user by id
@idAdd = 1
GET /users/{{idAdd}} HTTP/1.1
Host: localhost:8080

###

# Create user
POST /users HTTP/1.1
Host: localhost:8080

{
  "username": "itsna",
  "email": "itsna@mail.com",
  "password": "12345678"
}

###

# Edit user by id
@idEdit = 1
PATCH /users/{{idEdit}} HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "itsna2",
  "email": "itsna@mail.com",
}

###

# Delete user by id
@id = 1
DELETE  /users/{{id}} HTTP/1.1
Host: localhost:8080

###

# Register
POST /auth/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "itsna",
  "email": "itsna@mail.com",
  "password": "12345678"
}

###

# Login
POST /auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "email": "itsna@mail.com",
  "password": "123456789"
}

###

# Forgot password
@idForgot = 1
PATCH  /auth/forgot-password/{{{{idForgot}}}} HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "newPassword": "03062003"
}