# Get all data users
GET /users HTTP/1.1
Host: localhost:8080

###

# Get data user by id
@idAdd = 3
GET /users/{{idAdd}} HTTP/1.1
Host: localhost:8080

###

# Add data user
POST /users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": 8,
  "username": "Andi",
  "email" : "andi@mail.com",
  "password": "12345678"
}

###

# Edit data user by id
@idEdit = 1
PATCH /users/{{idEdit}} HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "Budi",
  "email": "budi@mail.com",
  "password": "12345563"
}

###

# Delete data user by id
@id = 1
DELETE  /users/{{id}} HTTP/1.1
Host: localhost:8080

###

# Register
POST /auth/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "Wisnu",
  "email": "wisnu@mail.com",
  "password": "123456"
}

###

# Login
POST /auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "email": "itsna@mail.com",
  "password": "123456789"
}